server:
  port: 8888
  servlet:
    context-path: /hejiayun
  tomcat:
    threads:
      min-spare: 30
      max: 800
    uri-encoding: UTF-8

logging:
  level:
    com.zgy: debug
    org.springframework: warn

mybatis-plus:
  type-aliases-package: com.zgy.hjy_community.**.domain
  mapper-locations: classpath:mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
#      这个指定id生成为雪花算法，我们可以使用@TableId指定我们的entity告诉我们框架这个主键，也可以在注解中使用`type`指定
      id-type: assign_id
    banner: false
spring:
  profiles:
#    激活application-druid配置文件
    active: druid

